### PR TITLE
Add rubocop autocorrect and check for config file existance

### PR DESCRIPTION
**Pull request by sergey-kintsel**
on `Ctrl+R` it will autocorrect whatever it can.
Also, you'll see a message that file doesn't exist when specified config file is absent.

### CODE REVIEW

**Comment by misogi** [comment]
Hi, thanks for your contribute.
Let me ask a question.

Is there any problem if execute --auto-correct when saving file? (file reload problem etc..)
I won't add shortcut keys. I worry about conflict with other extension and operation complexity.

I want to merge a message for file not exist.

**Comment by sergey-kintsel** [comment]
Hi, there should not be any issues with files. Because first, you save file, and only then RuboCop changes it to be correct.

**Comment by sergey-kintsel** [comment]
removed hotkey

**Comment by misogi** [comment]
I want to add an option autoCorrect (bool).
Then execute autocorrect when saving file if the option is true. (add no command)

Is this config helps your usage?

**Comment by sergey-kintsel** [comment]
No. I think we can add this option, but my solution should be added as well. For example, `rake db:migrate` in Rails creates `db/schema.rb` with it's own formatting that is not allowed by RuboCop.  But I don't want RuboCop change whole `db/schema.rb` if I change something there. I mean sometimes I don't want RuboCop doing anything

**Comment by misogi** [comment]
I got it.
I also checked Adding to exclude files on rubocop.yml was not solve this problem.

But I don't want to maintain two commands and two command-line option state for editing/saving on db/schema.rb that is often mistake.
Saving without change don't execute rubocop(= vscode's onDidSave event).

Would you use this solution?
- I will add autoCorrect option.
- You will turn off onSave option.
- You also add vscode shortcut setting (keybinding.json)

like :
``
{ "key": "shift+ctrl+r", "command": "ruby.rubocop", "when": "editorFocus" }
``

**Comment by sergey-kintsel** [comment]
I thought that I've turned off onSave option [here](https://github.com/misogi/vscode-ruby-rubocop/pull/24/files#diff-40be38a8cd7205d8ae3513904b98b3b8R4), haven't I? Also, I am not sure if I get you right. Why do we need this keybinding for `ruby.rubocop`? I would agree if it would be `{ "key": "shift+ctrl+r", "command": "ruby.rubocopAutocorrect"}` because I think that RuboCop check should be invoked each time when we save file, no? We can take a look at Sublime's RuboCop plugin. It runs rubocop check each time when we save a file, also, it provides separate command for autocorrect. WDYT?

**Comment by sergey-kintsel** [comment]
Also, it looks like we have a bug [here](https://github.com/misogi/vscode-ruby-rubocop/pull/24/files#diff-45327f86d4438556066de133327f4ca2R25), because `rubocop.isOnSave` is a function and it always be truthy...

**Comment by misogi** [comment]
I understood surely different invoke frequency of lint and auto correct.
If auto correct is heavy process we should not execute every saving.
And nobody may use shortcut for ruby.rubocop.

I will test branch on local repository and merge this pull request. 
Could you add default shortcut key for rubocopAutocorrect?

isOnSave is an Accessor. not a function.
https://www.typescriptlang.org/docs/handbook/classes.html

**Comment by sergey-kintsel** [comment]
done

**Pull request merged**
