### PR TITLE
Switch to --auto-correct-all

### PR DESCRIPTION
**Pull request by AlecRust**
Please see https://github.com/misogi/vscode-ruby-rubocop/issues/123, https://github.com/misogi/vscode-ruby-rubocop/issues/101.

### CODE REVIEW

**Comment by mgonc** [comment]
https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#0870-2020-07-06

**Comment by ngouy** [comment]
With newer version of rubocop (0.92) and fix about the json output (see https://github.com/misogi/vscode-ruby-rubocop/issues/129), I don't have any issue (all my files have a `frozen_string_literal: true` and auto correct is working).
Why must we run also unsafe corrections? I feel like auto correct unsafe corrections is, well, not safe, its more of an improvement.

Why is it a requirement?

Maybe we can try to add on option in the extension settings to toggle this behaviour?

**Comment by AlecRust** [comment]
@ngouy [I agree](https://github.com/misogi/vscode-ruby-rubocop/issues/101#issuecomment-696173224) it would be better to add an option for this. This PR fixes the behaviour to before the Rubocop change, but perhaps no longer necessary.

> I don't have any issue (all my files have a frozen_string_literal: true and auto correct is working).

Strange, my understanding was this cop was unsafe in terms of autocorrect (https://github.com/rubocop-hq/rubocop/pull/8529).

**Comment by ngouy** [comment]
Maybe I didn't quite understand the issue with the `frize_string_litteral` thing. Is the issue that you expect it to be autocorrected when you don't have it in your file? Or is the issue that when you have it the autocorrect doesn't works for other policies?

**Comment by AlecRust** [comment]
> Is the issue that you expect it to be autocorrected when you don't have it in your file?

Yes. This was the behaviour I experienced before this regression (caused by new Rubocop release).

**Comment by ngouy** [comment]
It's a real mess in issues, so much duplicates and sometimes many different bugs in a single one issue ^^' Hard to understand it all

**Comment by misogi** [comment]
Could you add an option (ex: safeAutoCorrect) that toggles `--auto-correct` or `--auto-correct-all`.

https://docs.rubocop.org/rubocop/usage/auto_correct.html

**Pull request closed without merging**
