### PR TITLE
Fix behavior of on open and close

### PR DESCRIPTION
**Pull request by ypresto**
- Lint files opened before the extension is loaded.
- Don't clear diagnostics of other files.
- Kill running rubocop process on close.
- Run single process at a time (to avoid accidential process bomb) (using queue).
  - This is caused by vscode's project-wide replace (opens all matched file at once).

### CODE REVIEW

**Comment by damien** [comment]
@ypresto This looks very nice, thanks for the contribution!

Two questions:
  1. It looks like you've removed some of the code that depends on ChildProcesses—could you verify if there are any remaining references to ChildProcess? If not, we should probably remove that as a dependency in this PR as well. :)
  2. `Task` and `TaskQueue` are nice additions—any chance we could get some test coverage for them? In particular, I'd love to see some tests documenting and verifying the TaskQueue implementation. I'm happy to assist if you need a hand with the tests.

Thanks again!

**Comment by ypresto** [comment]
Oh, I didn't realized that RubocopAutocorrect is extends Rubocop class. I want remove RubocopAutocorrect and add parameter to Rubocop constructor to pass `--auto-correct`.

**Comment by ypresto** [comment]
Added test..!

**Comment by ypresto** [comment]
vscode sometimes passes document with `git://` uri and `/path/to/file.git` fileName to open and close event (maybe bug...). So I added check for url scheme.

**Comment by ypresto** [comment]
I'm in doubt that TaskQueue should be replaced with more generic and reusable solution.
What I implemented is exactly same as the thing suggested in below URL.
https://github.com/caolan/async/issues/703

**Comment by damien** [comment]
This has improved a lot since I last saw this PR! Great work @ypresto!

This code look a pretty solid to me, so you have my :+1:. @misogi, can you check this out when you have some time? I think this work resolves a number of open bugs/feature requests around auto-correction and edit history.

**Comment by misogi** [comment]
Thanks for your great contribution!
I check behavior with replacing words in multiple files. Extension has been more solid.

It's exactly as you said, I want to there are solutions solve queuing by other libraries too.
Until then we find a solution. we will use taskQueue because stability is increased.
Let me know about alternative external library if you find them.

@damien Thanks for your helping on many discussion!
We have to solve an auto-correct issue. Surely this PR decrease unnecessary overwrite files !
It seems ChildProcess is still needed.

**Pull request merged**
